# Generated by Django 5.2.13 on 2026-05-05 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flashcardprogress',
            index=models.Index(fields=['user', 'next_review'], name='flashcards__user_id_bba208_idx'),
        ),
    ]
