# Generated by Django 5.2.13 on 2026-05-05 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='completedpracticequestion',
            index=models.Index(fields=['user', '-attempted_at'], name='quizzes_com_user_id_6ef30d_idx'),
        ),
        migrations.AddIndex(
            model_name='completedpracticequestion',
            index=models.Index(fields=['user', 'question'], name='quizzes_com_user_id_41864f_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-timestamp'], name='quizzes_qui_user_id_4fb0cb_idx'),
        ),
    ]
