# Generated by Django 5.2.13 on 2026-05-05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_bookmarkedquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='system',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='bookmarkedquestion',
            index=models.Index(fields=['user', 'question'], name='quizzes_boo_user_id_6fe660_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkedquestion',
            index=models.Index(fields=['user', '-created_at'], name='quizzes_boo_user_id_725fca_idx'),
        ),
    ]
