# Generated by Django 5.2.13 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_bookmarkedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam_tip',
            field=models.TextField(blank=True, default=''),
        ),
    ]
